config/routes.rb
Rails.application.routes.draw do
  resources :seatclasses
  resources :seats
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
    has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
    
end

app/models/seatclass.rb
class Seatclass < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:departure, :arrival, :destination, :baggage_allowance, :capacity)
    end
end

app/controllers/seatclasses_controller.rb
class SeatclassesController < ApplicationController
  before_action :set_seatclass, only: [:show, :edit, :update, :destroy]

  # GET /seatclasses
  # GET /seatclasses.json
  def index
    @seatclasses = Seatclass.all
  end

  # GET /seatclasses/1
  # GET /seatclasses/1.json
  def show
  end

  # GET /seatclasses/new
  def new
    @seatclass = Seatclass.new
  end

  # GET /seatclasses/1/edit
  def edit
  end

  # POST /seatclasses
  # POST /seatclasses.json
  def create
    @seatclass = Seatclass.new(seatclass_params)

    respond_to do |format|
      if @seatclass.save
        format.html { redirect_to @seatclass, notice: 'Seatclass was successfully created.' }
        format.json { render :show, status: :created, location: @seatclass }
      else
        format.html { render :new }
        format.json { render json: @seatclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seatclasses/1
  # PATCH/PUT /seatclasses/1.json
  def update
    respond_to do |format|
      if @seatclass.update(seatclass_params)
        format.html { redirect_to @seatclass, notice: 'Seatclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @seatclass }
      else
        format.html { render :edit }
        format.json { render json: @seatclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seatclasses/1
  # DELETE /seatclasses/1.json
  def destroy
    @seatclass.destroy
    respond_to do |format|
      format.html { redirect_to seatclasses_url, notice: 'Seatclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seatclass
      @seatclass = Seatclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seatclass_params
      params.require(:seatclass).permit(:class_name, :price, :food_sertvice, :seat_type, :leg_room)
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url, notice: 'Seat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_params
        params.require(:seat).permit(:flight_id, :name, :baggage, :seat_class_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/seatclasses_helper.rb
module SeatclassesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.datetime_select :arrival %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :baggage_allowance %>
    <%= form.text_field :baggage_allowance %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_list_seat.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/flights/_new_class.html.erb
<h1>New Seatclass</h1>

<%= render 'form', seatclass: @seatclass %>

<%= link_to 'Back', seatclasses_path %>

app/views/flights/_new_seat.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.number_field :flight_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<div class "field">
<%= form.label :flight_id %>
<%= form.collection_select(:seat_class_id, Seatclass.all, :id, :class_name, :prompt => 'Select Seat Class') %>
</div>

<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Departure</th>
      <th>Arrival</th>
      <th>Destination</th>
      <th>Baggage allowance</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.baggage_allowance %></td>
        <td><%= flight.capacity %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Baggage allowance:</strong>
  <%= @flight.baggage_allowance %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @flight.capacity %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

<h3>Seat Listing </h3>

<%= render partial: "list_seat", locals: {seats: @flight.seats} %>

<h3> New Seat </h3>

<%= render partial: "new_seat", locals:{seat:Seat.new(:flight_id => @flight.id)} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoconutAirWays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seatclasses/_form.html.erb
<%= form_with(model: seatclass, local: true) do |form| %>
  <% if seatclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seatclass.errors.count, "error") %> prohibited this seatclass from being saved:</h2>

      <ul>
      <% seatclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class_name %>
    <%= form.text_field :class_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :food_sertvice %>
    <%= form.check_box :food_sertvice %>
  </div>

  <div class="field">
    <%= form.label :seat_type %>
    <%= form.text_field :seat_type %>
  </div>

  <div class="field">
    <%= form.label :leg_room %>
    <%= form.number_field :leg_room %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seatclasses/edit.html.erb
<h1>Editing Seatclass</h1>

<%= render 'form', seatclass: @seatclass %>

<%= link_to 'Show', @seatclass %> |
<%= link_to 'Back', seatclasses_path %>

app/views/seatclasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seatclasses</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Price</th>
      <th>Food sertvice</th>
      <th>Seat type</th>
      <th>Leg room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seatclasses.each do |seatclass| %>
      <tr>
        <td><%= seatclass.class_name %></td>
        <td><%= seatclass.price %></td>
        <td><%= seatclass.food_sertvice %></td>
        <td><%= seatclass.seat_type %></td>
        <td><%= seatclass.leg_room %></td>
        <td><%= link_to 'Show', seatclass %></td>
        <td><%= link_to 'Edit', edit_seatclass_path(seatclass) %></td>
        <td><%= link_to 'Destroy', seatclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seatclass', new_seatclass_path %>

app/views/seatclasses/new.html.erb
<h1>New Seatclass</h1>

<%= render 'form', seatclass: @seatclass %>

<%= link_to 'Back', seatclasses_path %>

app/views/seatclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @seatclass.class_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @seatclass.price %>
</p>

<p>
  <strong>Food sertvice:</strong>
  <%= @seatclass.food_sertvice %>
</p>

<p>
  <strong>Seat type:</strong>
  <%= @seatclass.seat_type %>
</p>

<p>
  <strong>Leg room:</strong>
  <%= @seatclass.leg_room %>
</p>

<%= link_to 'Edit', edit_seatclass_path(@seatclass) %> |
<%= link_to 'Back', seatclasses_path %>

app/views/seats/_form.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.number_field :flight_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th>Class ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= seat.seat_class_id %></td>

        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight:</strong>
  <%= @seat.flight_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @seat.name %>
</p>

<p>
  <strong>Baggage:</strong>
  <%= @seat.baggage %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>